# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welteki
email: welteki@outlook.com
description: > Personal blog and website of Han Verstraete.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://welteki.com" # the base hostname & protocol for your site
twitter_username: welteki
github_username:  welteki
facebook_username: han.verstraete.9

# Build settings
markdown: kramdown

exclude: [node_modules, bower_components, package.json, bower.json, gulpfile.js, build.sh]
